server:
  port: 7070
  tomcat:
    threads:
      max: 100
      min-spare: 20
    accept-count: 200
    max-connections: 8192

spring:
  application:
    name: avatar-stub

avatar:
  # server | generate
  mode: server

  # Directory with generated JPEG avatars.
  dir: ./data/avatars

  # Used by generate mode.
  generate-count: 230000
  width: 550
  height: 550
  target-size-kb: 40
